import Strings from 'localized-strings';

// Strings.setLanguage('es')

const strings = new Strings({
    en: {
        cart: "cart",
        viewer: "viewer",
        filterBy: "filter by",
        firstName: "first name",
        lastName: "last name",
        search: "search",
        count: "count",
        noItems: "no {0}s",
        welcome: "$ref{word.welcome}!",
        viewCart: "$ref{word.view} $ref{cart}",
        noFirstName: "No first name",
        noLastName: "No last name",
        noFilter: "no filter",
        filtered: "filtered",
        none: "none",
        noName: "no name",
        provider: "provider",
        providers: "providers",
        users: "users",
        home: "home",
        settings: "settings",
        refresh: "refresh",
        word: {
            view: "view",
            found: "found",
            welcome: "Welcome",
        },
        pragCore: "Prag Core",
        pragCoreURL: "http://www.pragcore.com",
        aboutUs: "About Us",
        yearLastUpdated: "2019",
        Logout: "Logout",
        MyProfile: "{strings.MyProfile}",
        Settings: "Settings",
        Activity: "Activity",
        Support: "Support",

    },
    es: {
        cart: "carro",
        viewer: "visor",
        filterBy: "filtrar por",
        firstName: "nombre",
        lastName: "apellido",
        search: "buscar",
        count: "cuenta",
        noItems: "no {0}s",
        welcome: "Bienvenido",
        noFirstName: "sin nombre",
        noLastName: "sin apellido",
        noFilter: "sin filtro",
        filtered: "filtrado",
        none: "ninguno",
        noName: "sin nombre",
        provider: "proveedor",
        providers: "proveedores",
        users: "usuarios",
        home: "home",
        settings: "ajustes",
        refresh: "refrescar",
    }
})

export default strings